
WEATHER_API_MAP = {

    "Sunny":"sunny",
    "Clear":"clear",
    "Partly cloudy":"sunny_spells",
    "Cloudy":"cloudy",
    "Overcast":"overcast",
    "Mist":"cloudy",
    "Patchy rain possible":"rainy",
    "Patchy snow possible":"snowy",
    "Patchy sleet possible":"snowy",
    "Patchy freezing drizzle possible":"snowy",
    "Thundery outbreaks possible":"rainy",
    "Blowing snow":"snowy",
    "Blizzard":"snowy",
    "Fog":"cloudy",
    "Freezing fog":"cloudy",
    "Patchy light drizzle":"rainy",
    "Light drizzle":"rainy",
    "Freezing drizzle":"rainy",
    "Heavy freezing drizzle":"rainy",
    "Patchy light rain":"rainy",
    "Light rain":"rainy",
    "Moderate rain at times":"rainy",
    "Moderate rain":"rainy",
    "Heavy rain at times":"rainy",
    "Heavy rain":"rainy",
    "Light freezing rain":"rainy",
    "Moderate or heavy freezing rain":"rainy",
    "Light sleet":"snowy",
    "Moderate or heavy sleet":"snowy",
    "Patchy light snow":"snowy",
    "Light snow":"snowy",
    "Patchy moderate snow":"snowy",
    "Moderate snow":"snowy",
    "Patchy heavy snow":"snowy",
    "Heavy snow":"snowy",
    "Ice pellets":"snowy",
    "Light rain shower":"rainy",
    "Moderate or heavy rain shower":"rainy",
    "Torrential rain shower":"rainy",
    "Light sleet showers":"snowy",
    "Moderate or heavy sleet showers":"snowy",
    "Light snow showers":"snowy",
    "Moderate or heavy snow showers":"snowy",
    "Light showers of ice pellets":"snowy",
    "Moderate or heavy showers of ice pellets":"snowy",
    "Patchy light rain with thunder":"rainy",
    "Moderate or heavy rain with thunder":"rainy",
    "Patchy light snow with thunder":"snowy",
    "Moderate or heavy snow with thunder":"snowy"
}


